#ifndef CLOD_WORKGRAPH_ROOT_CONSTANTS_H
#define CLOD_WORKGRAPH_ROOT_CONSTANTS_H

#define CLOD_WG_VIEW_RASTER_INFO_BUFFER_DESCRIPTOR_INDEX UintRootConstant0
#define CLOD_WG_SW_VISIBLE_CLUSTERS_COUNTER_DESCRIPTOR_INDEX UintRootConstant1
#define CLOD_WG_VISIBLE_CLUSTERS_BUFFER_DESCRIPTOR_INDEX UintRootConstant2
#define CLOD_WG_VISIBLE_CLUSTERS_COUNTER_DESCRIPTOR_INDEX UintRootConstant3
#define CLOD_WG_HW_WRITE_BASE_COUNTER_DESCRIPTOR_INDEX UintRootConstant4
#define CLOD_WG_OCCLUSION_REPLAY_BUFFER_DESCRIPTOR_INDEX UintRootConstant5
#define CLOD_WG_OCCLUSION_REPLAY_STATE_DESCRIPTOR_INDEX UintRootConstant6
#define CLOD_WG_WORKGRAPH_NODE_INPUTS_DESCRIPTOR_INDEX UintRootConstant7
#define CLOD_WG_VIEW_DEPTH_SRV_INDICES_DESCRIPTOR_INDEX UintRootConstant8
#define CLOD_WG_FLAGS UintRootConstant9
#define CLOD_WG_TELEMETRY_DESCRIPTOR_INDEX UintRootConstant10
#define CLOD_WG_VISIBLE_CLUSTERS_CAPACITY UintRootConstant11
#define CLOD_WG_SHADOW_DIRTY_HIERARCHY_DESCRIPTOR_INDEX UintRootConstant12
#define CLOD_WG_SW_WRITE_BASE_COUNTER_DESCRIPTOR_INDEX UintRootConstant13
#define CLOD_WG_SHADOW_INVALIDATED_INSTANCES_DESCRIPTOR_INDEX UintRootConstant14
#define CLOD_WG_SHADOW_PREDICTIVE_INVALIDATION_CANDIDATES_DESCRIPTOR_INDEX UintRootConstant15
#define CLOD_WG_SHADOW_PREDICTIVE_INVALIDATION_CANDIDATE_COUNT_DESCRIPTOR_INDEX UintRootConstant16
#define CLOD_WG_PAGE_JOB_FLAGS UintRootConstant17
#define CLOD_WG_VIRTUAL_SHADOW_PAGE_TABLE_UAV_DESCRIPTOR_INDEX UintRootConstant18
#define CLOD_WG_VIRTUAL_SHADOW_PHYSICAL_PAGES_UAV_DESCRIPTOR_INDEX UintRootConstant19
#define CLOD_WG_REYES_DICE_QUEUE_DESCRIPTOR_INDEX UintRootConstant20
#define CLOD_WG_REYES_DICE_QUEUE_COUNTER_DESCRIPTOR_INDEX UintRootConstant21
#define CLOD_WG_REYES_DICE_QUEUE_OVERFLOW_DESCRIPTOR_INDEX UintRootConstant22
#define CLOD_WG_REYES_TESS_TABLE_CONFIGS_DESCRIPTOR_INDEX UintRootConstant23
#define CLOD_WG_REYES_TESS_TABLE_VERTICES_DESCRIPTOR_INDEX UintRootConstant24
#define CLOD_WG_REYES_TESS_TABLE_TRIANGLES_DESCRIPTOR_INDEX UintRootConstant25
#define CLOD_WG_FORCED_TRAVERSAL_DEPTH_ROOT UintRootConstant26
#define CLOD_WG_REYES_TELEMETRY_DESCRIPTOR_INDEX UintRootConstant27
#define CLOD_WG_REYES_DICE_QUEUE_CAPACITY UintRootConstant28
#define CLOD_WG_VISIBLE_CLUSTER_TRANSFORM_INDICES_DESCRIPTOR_INDEX UintRootConstant29

#define CLOD_WG_FORCED_TRAVERSAL_DEPTH_ROOT_DISABLED 0xFFFFFFFFu

#define CLOD_WG_FLAG_TELEMETRY_ENABLED (1u << 0)
#define CLOD_WG_FLAG_OCCLUSION_ENABLED (1u << 1)
#define CLOD_WG_FLAG_SW_RASTER_ENABLED (1u << 2)
#define CLOD_WG_FLAG_PHASE2 (1u << 3)
#define CLOD_WG_FLAG_COMPUTE_SW_RASTER (1u << 4)
#define CLOD_WG_FLAG_DISABLE_SHADOW_DIRTY_PAGE_CULLING (1u << 5)
#define CLOD_WG_FLAG_VSM_PREDICTIVE_LOD_INVALIDATION (1u << 6)
#define CLOD_WG_FLAG_DISABLE_FRUSTUM_CULLING (1u << 7)
#define CLOD_WG_SW_RASTER_THRESHOLD_SHIFT 16

// Page-job VSM flags packed into CLOD_WG_PAGE_JOB_FLAGS:
//   bit 0       = page-job enabled
//   bit 1       = force all opaque VSM clusters through page-job path
//   bits [15:8] = diameter threshold (0-255 pixels)
//   bits [23:16] = sparse ratio numerator (0-255, ratio = value/255)
//   bits [31:24] = max dirty pages per cluster (0-255, 0 = use default 32)
#define CLOD_WG_PAGE_JOB_FLAG_ENABLED (1u << 0)
#define CLOD_WG_PAGE_JOB_FLAG_FORCE_ALL (1u << 1)
#define CLOD_WG_PAGE_JOB_DIAMETER_THRESHOLD_SHIFT 8
#define CLOD_WG_PAGE_JOB_DIAMETER_THRESHOLD_MASK 0xFF00u
#define CLOD_WG_PAGE_JOB_SPARSE_RATIO_SHIFT 16
#define CLOD_WG_PAGE_JOB_SPARSE_RATIO_MASK 0xFF0000u
#define CLOD_WG_PAGE_JOB_MAX_PAGES_SHIFT 24
#define CLOD_WG_PAGE_JOB_MAX_PAGES_MASK 0xFF000000u

#endif // CLOD_WORKGRAPH_ROOT_CONSTANTS_H
