#pragma once

#define AS_THREADS_PER_WAVE 32
#define AS_GROUP_SIZE AS_THREADS_PER_WAVE
#define MS_THREAD_GROUP_SIZE 32
#define MS_MESHLET_SIZE 128
#define MS_MESHLET_MIN_SIZE 64

// Cluster LOD page-tile constants
#define CLOD_MAX_CLUSTERS_PER_GROUP 512
#define CLOD_PAGE_SIZE 256*1024
#define CLOD_PAGE_HEADER_SIZE 64        // 16 x uint32
#define CLOD_MESHLET_DESCRIPTOR_SIZE 48  // 12 x uint32 = 3 x Load4
