// CLodCacheTool - Offline ClusterLOD cache builder
//
// Usage:  CLodCacheTool <file1> [file2 ...]
//
// Supported formats (auto-detected by extension):
//   .usd / .usda / .usdc / .usdz    -> USD
//   .gltf / .glb                     -> glTF
//   .nif                             -> BRNifly -> USD
//   anything else (fbx, obj, ...)    -> Assimp
//
// Caches are written to the same location the renderer would use,
// so a subsequent renderer launch will hit the cache instead of rebuilding.

#include <algorithm>
#include <atomic>
#include <cctype>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <functional>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <mutex>
#include <numeric>
#include <string>
#include <unordered_set>
#include <unordered_map>
#include <vector>

#include <nlohmann/json.hpp>

#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <tracy/Tracy.hpp>

#include "Managers/Singletons/TaskSchedulerManager.h"
#include "Import/GlTFGeometryExtractor.h"
#include "Import/AssimpGeometryExtractor.h"
#include "Import/USDGeometryExtractor.h"
#include "Import/USDMaterialCache.h"
#include "Import/BRNiflyClient.h"
#include "Utilities/CachePathUtilities.h"

#include <pxr/usd/sdf/layer.h>
#include <pxr/usd/usd/primFlags.h>
#include <pxr/usd/usd/primRange.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usdGeom/imageable.h>
#include <pxr/usd/usdGeom/mesh.h>
#include <pxr/usd/usdGeom/pointInstancer.h>
#include <pxr/usd/usdGeom/subset.h>
#include <pxr/usd/usdGeom/xformCache.h>
#include <pxr/usd/usdShade/materialBindingAPI.h>

namespace fs = std::filesystem;

static bool g_reportEnabled = false;
static fs::path g_reportPath;
static bool g_reportInitialized = false;
static std::mutex g_reportMutex;
static uint32_t g_usdTessellationFactor = 1u;
static fs::path g_assetOverridesConfig;
static std::unordered_map<std::string, std::string> g_sourceIdentifierOverrides;

// Helpers

static std::string ToLower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return s;
}

enum class AssetFormat { USD, GlTF, Nif, Assimp };

static AssetFormat DetectFormat(const fs::path& path) {
    auto ext = ToLower(path.extension().string());
    if (ext == ".usd" || ext == ".usda" || ext == ".usdc" || ext == ".usdz")
        return AssetFormat::USD;
    if (ext == ".gltf" || ext == ".glb")
        return AssetFormat::GlTF;
	if (ext == ".nif" || ext == ".bto")
        return AssetFormat::Nif;
    return AssetFormat::Assimp;   // fbx, obj, dae, ...
}

static const char* FormatName(AssetFormat f) {
    switch (f) {
        case AssetFormat::USD:   return "USD";
        case AssetFormat::GlTF:  return "glTF";
        case AssetFormat::Nif: return "NIF";
        case AssetFormat::Assimp: return "Assimp";
    }
    return "?";
}

static void SetProcessEnvironment(const char* name, const std::string& value) {
#if defined(_WIN32)
    _putenv_s(name, value.c_str());
#else
    setenv(name, value.c_str(), 1);
#endif
}

static std::string WideToUtf8Lossy(const std::wstring& value) {
    std::string result;
    result.reserve(value.size());
    for (wchar_t ch : value) {
        result.push_back(ch >= 0 && ch <= 0x7f ? static_cast<char>(ch) : '?');
    }
    return result;
}

static const char* NodeKindName(uint32_t kind) {
    switch (kind) {
    case CLOD_NODE_INTERNAL: return "internal";
    case CLOD_NODE_VOXEL_LEAF: return "voxel-leaf";
    case CLOD_NODE_SEGMENT_LEAF: return "segment-leaf";
    case CLOD_NODE_INSTANCE_ROOT: return "instance-root";
    default: return "invalid";
    }
}

static std::string CanonicalPathKey(const fs::path& path) {
    std::error_code ec;
    auto canonical = fs::weakly_canonical(path, ec);
    if (ec)
        canonical = fs::absolute(path).lexically_normal();
    return ToLower(canonical.generic_string());
}

static std::string NormalizeLogicalAssetPath(std::string path) {
    std::replace(path.begin(), path.end(), '/', '\\');
    while (!path.empty() && (path.front() == '\\' || path.front() == '/'))
        path.erase(path.begin());
    return path;
}

static bool EnsureClusterLODReportInitialized() {
    if (!g_reportEnabled) {
        return false;
    }

    if (!g_reportInitialized) {
        if (!g_reportPath.parent_path().empty()) {
            fs::create_directories(g_reportPath.parent_path());
        }
        std::ofstream reset(g_reportPath, std::ios::trunc);
        if (!reset) {
            spdlog::warn("Unable to initialize CLOD report '{}'", g_reportPath.string());
            return false;
        }
        reset << "ClusterLOD diagnostics report\n";
        reset << "Generated by CLodCacheTool\n\n";
        g_reportInitialized = true;
    }

    return true;
}

static pxr::UsdTimeCode GetUsdGeometrySampleTime(const pxr::UsdStageRefPtr& stage) {
    if (stage && stage->HasAuthoredTimeCodeRange()) {
        return pxr::UsdTimeCode(stage->GetStartTimeCode());
    }

    return pxr::UsdTimeCode::Default();
}

static uint64_t CountUsdMeshSourceTriangles(
    const pxr::UsdGeomMesh& mesh,
    pxr::UsdTimeCode geomTimeCode) {
    pxr::VtArray<int> faceVertCounts;
    if (!mesh.GetFaceVertexCountsAttr().Get(&faceVertCounts, geomTimeCode)) {
        return 0;
    }

    pxr::VtArray<int> holeIndices;
    if (mesh.GetHoleIndicesAttr()) {
        mesh.GetHoleIndicesAttr().Get(&holeIndices, geomTimeCode);
    }

    std::vector<uint8_t> holedFaces(faceVertCounts.size(), 0u);
    for (int holeFaceIndex : holeIndices) {
        if (holeFaceIndex >= 0 && static_cast<size_t>(holeFaceIndex) < holedFaces.size()) {
            holedFaces[static_cast<size_t>(holeFaceIndex)] = 1u;
        }
    }

    uint64_t triangleCount = 0;
    for (size_t faceIndex = 0; faceIndex < faceVertCounts.size(); ++faceIndex) {
        if (holedFaces[faceIndex] != 0u) {
            continue;
        }

        const int faceVertexCount = faceVertCounts[faceIndex];
        if (faceVertexCount >= 3) {
            triangleCount += static_cast<uint64_t>(faceVertexCount - 2);
        }
    }

    return triangleCount;
}

static uint64_t CountUsdStageSourceTriangles(const pxr::UsdStageRefPtr& stage) {
    if (!stage) {
        return 0;
    }

    const pxr::UsdTimeCode geomTimeCode = GetUsdGeometrySampleTime(stage);
    uint64_t triangleCount = 0;

    std::function<void(const pxr::UsdPrim&)> visitPrim = [&](const pxr::UsdPrim& prim) {
        const pxr::UsdGeomMesh mesh(prim);
        if (mesh) {
            triangleCount += CountUsdMeshSourceTriangles(mesh, geomTimeCode);
        }

        for (const pxr::UsdPrim& child : prim.GetFilteredChildren(pxr::UsdTraverseInstanceProxies())) {
            visitPrim(child);
        }
    };

    visitPrim(stage->GetPseudoRoot());
    return triangleCount;
}

static bool PathHasAnyPrefix(const pxr::SdfPath& path, const std::vector<pxr::SdfPath>& prefixes) {
    for (const pxr::SdfPath& prefix : prefixes) {
        if (path.HasPrefix(prefix)) {
            return true;
        }
    }
    return false;
}

static std::string JoinStrings(const std::vector<std::string>& values, size_t limit = 16u) {
    std::string joined;
    const size_t count = std::min(values.size(), limit);
    for (size_t i = 0; i < count; ++i) {
        if (!joined.empty()) {
            joined += ";";
        }
        joined += values[i];
    }
    if (values.size() > limit) {
        joined += ";...";
    }
    return joined;
}

struct UsdPrototypeMeshStats {
    uint32_t meshCount = 0u;
    uint32_t subsetCount = 0u;
    uint64_t sourceTriangles = 0u;
    std::vector<std::string> meshPaths;
};

static UsdPrototypeMeshStats GatherUsdPrototypeMeshStats(
    const pxr::UsdPrim& root,
    pxr::UsdTimeCode geomTimeCode) {
    UsdPrototypeMeshStats stats;
    std::function<void(const pxr::UsdPrim&)> visit = [&](const pxr::UsdPrim& prim) {
        if (prim.IsA<pxr::UsdGeomImageable>()) {
            pxr::UsdGeomImageable imageable(prim);
            if (imageable.ComputeVisibility(geomTimeCode) == pxr::UsdGeomTokens->invisible) {
                return;
            }
        }

        pxr::UsdGeomMesh mesh(prim);
        if (mesh) {
            ++stats.meshCount;
            stats.sourceTriangles += CountUsdMeshSourceTriangles(mesh, geomTimeCode);
            pxr::UsdShadeMaterialBindingAPI bindAPI(mesh);
            stats.subsetCount += static_cast<uint32_t>(bindAPI.GetMaterialBindSubsets().size());
            stats.meshPaths.push_back(prim.GetPath().GetString());
        }

        for (const pxr::UsdPrim& child : prim.GetFilteredChildren(pxr::UsdTraverseInstanceProxies())) {
            visit(child);
        }
    };

    if (root) {
        visit(root);
    }
    return stats;
}

static void WriteUsdAssemblyReport(
    const fs::path& sourcePath,
    std::string_view label,
    const pxr::UsdStageRefPtr& stage) {
    std::scoped_lock reportLock(g_reportMutex);
    if (!EnsureClusterLODReportInitialized() || !stage) {
        return;
    }

    const pxr::UsdTimeCode geomTimeCode = GetUsdGeometrySampleTime(stage);
    std::vector<pxr::UsdGeomPointInstancer> pointInstancers;
    std::vector<pxr::SdfPath> prototypeRoots;
    std::unordered_set<std::string> prototypeRootStrings;

    auto pointInstancerPrimRange = pxr::UsdPrimRange(stage->GetPseudoRoot());
    for (auto primIt = pointInstancerPrimRange.begin(); primIt != pointInstancerPrimRange.end(); ++primIt) {
        pxr::UsdGeomPointInstancer pointInstancer(*primIt);
        if (!pointInstancer) {
            continue;
        }

        pointInstancers.push_back(pointInstancer);
        pxr::SdfPathVector targets;
        if (pointInstancer.GetPrototypesRel().GetTargets(&targets)) {
            for (const pxr::SdfPath& target : targets) {
                if (prototypeRootStrings.insert(target.GetString()).second) {
                    prototypeRoots.push_back(target);
                }
            }
        }
    }

    struct RootMeshRow {
        std::string path;
        uint32_t subsets = 0u;
        uint64_t sourceTriangles = 0u;
    };
    std::vector<RootMeshRow> rootMeshes;
    auto rootMeshPrimRange = pxr::UsdPrimRange(stage->GetPseudoRoot());
    for (auto primIt = rootMeshPrimRange.begin(); primIt != rootMeshPrimRange.end(); ++primIt) {
        pxr::UsdGeomMesh mesh(*primIt);
        if (!mesh || PathHasAnyPrefix(mesh.GetPrim().GetPath(), prototypeRoots)) {
            continue;
        }

        pxr::UsdShadeMaterialBindingAPI bindAPI(mesh);
        rootMeshes.push_back(RootMeshRow{
            .path = mesh.GetPrim().GetPath().GetString(),
            .subsets = static_cast<uint32_t>(bindAPI.GetMaterialBindSubsets().size()),
            .sourceTriangles = CountUsdMeshSourceTriangles(mesh, geomTimeCode),
        });
    }

    uint64_t totalInstances = 0u;
    for (const pxr::UsdGeomPointInstancer& pointInstancer : pointInstancers) {
        pxr::VtIntArray protoIndices;
        if (!pointInstancer.GetProtoIndicesAttr().Get(&protoIndices, geomTimeCode)) {
            continue;
        }
        std::vector<bool> mask = pointInstancer.ComputeMaskAtTime(geomTimeCode);
        if (!mask.empty()) {
            pxr::UsdGeomPointInstancer::ApplyMaskToArray(mask, &protoIndices);
        }
        totalInstances += protoIndices.size();
    }

    std::ofstream out(g_reportPath, std::ios::app);
    if (!out) {
        spdlog::warn("Unable to open CLOD report '{}'", g_reportPath.string());
        return;
    }

    out << "=== USD assembly candidates: " << label << " ===\n";
    out << "source," << sourcePath.string() << "\n";
    out << "summary,point_instancers,prototype_roots,emitted_instances,root_meshes,geometry_time\n";
    out << "summary,"
        << pointInstancers.size() << ","
        << prototypeRoots.size() << ","
        << totalInstances << ","
        << rootMeshes.size() << ","
        << (geomTimeCode.IsDefault() ? -1.0 : geomTimeCode.GetValue()) << "\n";

    out << "\nUSD assembly root mesh candidates:\n";
    out << "mesh_path,material_subsets,source_triangles\n";
    for (const RootMeshRow& row : rootMeshes) {
        out << row.path << "," << row.subsets << "," << row.sourceTriangles << "\n";
    }

    out << "\nUSD point instancers:\n";
    out << "instancer,path,prototype_count,instance_count,valid_transform_count,nesting_depth\n";
    uint32_t instancerIndex = 0u;
    for (const pxr::UsdGeomPointInstancer& pointInstancer : pointInstancers) {
        pxr::SdfPathVector prototypeTargets;
        pointInstancer.GetPrototypesRel().GetTargets(&prototypeTargets);

        pxr::VtIntArray protoIndices;
        if (!pointInstancer.GetProtoIndicesAttr().Get(&protoIndices, geomTimeCode)) {
            protoIndices.clear();
        }
        std::vector<bool> mask = pointInstancer.ComputeMaskAtTime(geomTimeCode);
        if (!mask.empty()) {
            pxr::UsdGeomPointInstancer::ApplyMaskToArray(mask, &protoIndices);
        }

        pxr::VtArray<pxr::GfMatrix4d> instanceTransforms;
        const bool transformsValid = pointInstancer.ComputeInstanceTransformsAtTime(
            &instanceTransforms,
            geomTimeCode,
            geomTimeCode,
            pxr::UsdGeomPointInstancer::IncludeProtoXform,
            pxr::UsdGeomPointInstancer::ApplyMask);
        const size_t emittedCount = std::min(protoIndices.size(), transformsValid ? instanceTransforms.size() : size_t(0u));
        const uint32_t nestingDepth = 1u;

        out << instancerIndex << ","
            << pointInstancer.GetPrim().GetPath().GetString() << ","
            << prototypeTargets.size() << ","
            << protoIndices.size() << ","
            << (transformsValid ? instanceTransforms.size() : 0u) << ","
            << nestingDepth << "\n";

        std::vector<uint32_t> usageByPrototype(prototypeTargets.size(), 0u);
        for (int protoIndex : protoIndices) {
            if (protoIndex >= 0 && static_cast<size_t>(protoIndex) < usageByPrototype.size()) {
                usageByPrototype[static_cast<size_t>(protoIndex)]++;
            }
        }

        out << "\nUSD point instancer prototype usage " << instancerIndex << ":\n";
        out << "prototype,target,mesh_count,material_subsets,source_triangles,instances,mesh_paths\n";
        for (uint32_t prototypeIndex = 0u; prototypeIndex < static_cast<uint32_t>(prototypeTargets.size()); ++prototypeIndex) {
            const pxr::UsdPrim prototypeRoot = stage->GetPrimAtPath(prototypeTargets[prototypeIndex]);
            const UsdPrototypeMeshStats stats = GatherUsdPrototypeMeshStats(prototypeRoot, geomTimeCode);
            out << prototypeIndex << ","
                << prototypeTargets[prototypeIndex].GetString() << ","
                << stats.meshCount << ","
                << stats.subsetCount << ","
                << stats.sourceTriangles << ","
                << usageByPrototype[prototypeIndex] << ","
                << JoinStrings(stats.meshPaths) << "\n";
        }

        out << "\nUSD point instancer transforms " << instancerIndex << " (first 256):\n";
        out << "instance,prototype,target,translation_x,translation_y,translation_z,row0_x,row0_y,row0_z,row0_w,row1_x,row1_y,row1_z,row1_w,row2_x,row2_y,row2_z,row2_w\n";
        for (uint32_t instanceIndex = 0u; instanceIndex < emittedCount && instanceIndex < 256u; ++instanceIndex) {
            const int protoIndex = protoIndices[instanceIndex];
            const pxr::SdfPath* target = protoIndex >= 0 && static_cast<size_t>(protoIndex) < prototypeTargets.size()
                ? &prototypeTargets[static_cast<size_t>(protoIndex)]
                : nullptr;
            const pxr::GfMatrix4d& matrix = instanceTransforms[instanceIndex];
            const pxr::GfVec3d translation = matrix.ExtractTranslation();
            out << instanceIndex << ","
                << protoIndex << ","
                << (target ? target->GetString() : "invalid") << ","
                << translation[0] << "," << translation[1] << "," << translation[2] << ","
                << matrix[0][0] << "," << matrix[0][1] << "," << matrix[0][2] << "," << matrix[0][3] << ","
                << matrix[1][0] << "," << matrix[1][1] << "," << matrix[1][2] << "," << matrix[1][3] << ","
                << matrix[2][0] << "," << matrix[2][1] << "," << matrix[2][2] << "," << matrix[2][3] << "\n";
        }

        out << "\n";
        ++instancerIndex;
    }

    out << "\n";
}

static bool SphereFinite(const DirectX::XMFLOAT4& s) {
    return std::isfinite(s.x) && std::isfinite(s.y) && std::isfinite(s.z) && std::isfinite(s.w);
}

static void WriteClusterLODReport(
    const fs::path& sourcePath,
    std::string_view label,
    const MeshPreprocessResult& meshResult) {
    std::scoped_lock reportLock(g_reportMutex);
    if (!g_reportEnabled || !meshResult.prebuiltData.has_value()) {
        return;
    }

    if (!EnsureClusterLODReportInitialized()) {
        return;
    }

    std::ofstream out(g_reportPath, std::ios::app);
    if (!out) {
        spdlog::warn("Unable to open CLOD report '{}'", g_reportPath.string());
        return;
    }

    const ClusterLODPrebuiltData& data = *meshResult.prebuiltData;
    const auto& groups = data.groups;
    const auto& segments = data.segments;
    const auto& nodes = data.nodes;

    std::map<int32_t, uint32_t> groupsByDepth;
    std::map<int32_t, uint64_t> meshletsByDepth;
    std::map<int32_t, uint64_t> terminalSegmentsByDepth;
    uint32_t voxelGroups = 0;
    uint32_t assemblyProxyGroups = 0;
    uint32_t assemblyVoxelGroups = 0;
    int32_t maxAssemblyVoxelDepth = -1;
    uint32_t refinedEdges = 0;
    uint32_t terminalSegments = 0;
    uint32_t invalidSegmentRanges = 0;
    uint32_t invalidRefinedGroups = 0;
    uint32_t refinedEdgesToLowerDepth = 0;
    uint32_t refinedEdgesToSameOrHigherDepth = 0;
    uint32_t nonSelectedParentEdges = 0;
    uint32_t finiteGroupErrorIssues = 0;
    uint32_t lodSphereContainmentViolations = 0;
    float maxLodSphereEscape = 0.0f;
    float minGroupError = std::numeric_limits<float>::max();
    float maxGroupError = 0.0f;
    float maxParentToOwnErrorRatio = 0.0f;
    std::vector<uint32_t> parentRefCounts(groups.size(), 0u);
    std::vector<float> maxDirectParentError(groups.size(), 0.0f);

    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()); ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        groupsByDepth[group.depth]++;
        meshletsByDepth[group.depth] += group.meshletCount;
        terminalSegmentsByDepth[group.depth] += group.terminalSegmentCount;
        voxelGroups += (group.flags & CLOD_GROUP_FLAG_IS_VOXEL) != 0u ? 1u : 0u;
        assemblyProxyGroups += (group.flags & CLOD_GROUP_FLAG_IS_ASSEMBLY_PROXY) != 0u ? 1u : 0u;
        if ((group.flags & CLOD_GROUP_FLAG_IS_ASSEMBLY_VOXEL) != 0u) {
            assemblyVoxelGroups++;
            maxAssemblyVoxelDepth = std::max(maxAssemblyVoxelDepth, group.depth);
        }
        terminalSegments += group.terminalSegmentCount;

        if (!std::isfinite(group.bounds.error) || group.bounds.error < 0.0f ||
            !std::isfinite(group.maxParentError) || group.maxParentError < 0.0f) {
            finiteGroupErrorIssues++;
        }
        minGroupError = std::min(minGroupError, group.bounds.error);
        maxGroupError = std::max(maxGroupError, group.bounds.error);
        if (group.bounds.error > 0.0f && std::isfinite(group.maxParentError) &&
            group.maxParentError < std::numeric_limits<float>::max() * 0.5f) {
            maxParentToOwnErrorRatio = std::max(maxParentToOwnErrorRatio, group.maxParentError / group.bounds.error);
        }

        if (group.firstSegment + group.segmentCount > segments.size()) {
            invalidSegmentRanges++;
            continue;
        }

        for (uint32_t offset = 0; offset < group.segmentCount; ++offset) {
            const ClusterLODGroupSegment& segment = segments[group.firstSegment + offset];
            if (segment.refinedGroup < 0) {
                continue;
            }

            refinedEdges++;
            const uint32_t childGroupIndex = static_cast<uint32_t>(segment.refinedGroup);
            if (childGroupIndex >= groups.size()) {
                invalidRefinedGroups++;
                continue;
            }

            const ClusterLODGroup& child = groups[childGroupIndex];
            const float dx = child.bounds.center[0] - group.bounds.center[0];
            const float dy = child.bounds.center[1] - group.bounds.center[1];
            const float dz = child.bounds.center[2] - group.bounds.center[2];
            const float escape =
                std::sqrt(dx * dx + dy * dy + dz * dz) +
                child.bounds.radius -
                group.bounds.radius;
            if (escape > std::max(1.0e-5f, group.bounds.radius * 1.0e-5f)) {
                lodSphereContainmentViolations++;
                maxLodSphereEscape = std::max(maxLodSphereEscape, escape);
            }
            if (child.depth < group.depth) {
                refinedEdgesToLowerDepth++;
            }
            else {
                refinedEdgesToSameOrHigherDepth++;
            }
            parentRefCounts[childGroupIndex]++;
            maxDirectParentError[childGroupIndex] = std::max(maxDirectParentError[childGroupIndex], group.bounds.error);
            if (child.parentGroupId != static_cast<int32_t>(groupIndex)) {
                nonSelectedParentEdges++;
            }
        }
    }
    if (groups.empty()) {
        minGroupError = 0.0f;
    }

    uint32_t internalNodes = 0;
    uint32_t segmentLeafNodes = 0;
    uint32_t voxelLeafNodes = 0;
    uint32_t instanceRootNodes = 0;
    uint32_t invalidNodeKinds = 0;
    uint32_t invalidNodeRanges = 0;
    uint32_t invalidLeafOwners = 0;
    uint32_t invalidLeafSegments = 0;
    uint32_t invalidAssemblyInstances = 0;
    uint32_t invalidAssemblyTargets = 0;
    uint32_t invalidAssemblyTransforms = 0;
    uint32_t excessiveAssemblyDepth = 0;
    uint32_t instanceRootMaxStackDepth = 0;
    uint32_t nonFiniteNodeMetrics = 0;
    uint32_t internalMaxErrorViolations = 0;
    std::unordered_map<uint32_t, uint32_t> segmentLeafRefs;
    std::unordered_map<uint32_t, uint32_t> groupLeafRefs;
    std::vector<uint8_t> reachable(nodes.size(), 0u);
    std::vector<uint32_t> stack;
    if (!nodes.empty()) {
        stack.push_back(0u);
    }
    while (!stack.empty()) {
        const uint32_t nodeIndex = stack.back();
        stack.pop_back();
        if (nodeIndex >= nodes.size() || reachable[nodeIndex] != 0u) {
            continue;
        }
        reachable[nodeIndex] = 1u;
        const ClusterLODNode& node = nodes[nodeIndex];
        if (!SphereFinite(node.traversalMetric.cullingSphere) ||
            !SphereFinite(node.traversalMetric.lodBoundingSphere) ||
            !std::isfinite(node.traversalMetric.maxQuadricError)) {
            nonFiniteNodeMetrics++;
        }

        if (node.range.isGroup == CLOD_NODE_INTERNAL) {
            internalNodes++;
            const uint32_t childCount = node.range.countMinusOne + 1u;
            if (childCount == 0u || node.range.indexOrOffset + childCount > nodes.size()) {
                invalidNodeRanges++;
                continue;
            }
            float maxChildError = 0.0f;
            for (uint32_t childOffset = 0; childOffset < childCount; ++childOffset) {
                const uint32_t childIndex = node.range.indexOrOffset + childOffset;
                maxChildError = std::max(maxChildError, nodes[childIndex].traversalMetric.maxQuadricError);
                stack.push_back(childIndex);
            }
            if (node.traversalMetric.maxQuadricError + 1.0e-8f < maxChildError) {
                internalMaxErrorViolations++;
            }
        }
        else if (node.range.isGroup == CLOD_NODE_SEGMENT_LEAF) {
            segmentLeafNodes++;
            groupLeafRefs[node.range.ownerGroupId]++;
            segmentLeafRefs[node.range.indexOrOffset]++;
            if (node.range.ownerGroupId >= groups.size()) {
                invalidLeafOwners++;
            }
            if (node.range.indexOrOffset >= segments.size()) {
                invalidLeafSegments++;
            }
        }
        else if (node.range.isGroup == CLOD_NODE_VOXEL_LEAF) {
            voxelLeafNodes++;
            groupLeafRefs[node.range.ownerGroupId]++;
            if (node.range.ownerGroupId >= groups.size()) {
                invalidLeafOwners++;
            }
        }
        else if (node.range.isGroup == CLOD_NODE_INSTANCE_ROOT) {
            instanceRootNodes++;
            if (node.range.indexOrOffset >= data.assemblyInstances.size()) {
                invalidAssemblyInstances++;
                continue;
            }

            const ClusterLODAssemblyInstance& instance = data.assemblyInstances[node.range.indexOrOffset];
            instanceRootMaxStackDepth = std::max(instanceRootMaxStackDepth, instance.stackDepth);
            if (instance.targetRootNode >= nodes.size()) {
                invalidAssemblyTargets++;
            }
            else {
                stack.push_back(instance.targetRootNode);
            }
            if (instance.transformIndex != CLOD_ASSEMBLY_TRANSFORM_SENTINEL &&
                instance.transformIndex >= data.assemblyTransforms.size()) {
                invalidAssemblyTransforms++;
            }
            if (instance.stackDepth > CLOD_ASSEMBLY_MAX_STACK_DEPTH) {
                excessiveAssemblyDepth++;
            }
        }
        else {
            invalidNodeKinds++;
        }
    }

    uint32_t unreachableNodes = 0;
    for (uint8_t v : reachable) {
        unreachableNodes += v == 0u ? 1u : 0u;
    }
    uint32_t duplicateSegmentLeafRefs = 0;
    for (const auto& [segmentIndex, refCount] : segmentLeafRefs) {
        duplicateSegmentLeafRefs += refCount > 1u ? 1u : 0u;
    }

    out << "=== " << label << " ===\n";
    out << "Source: " << fs::weakly_canonical(sourcePath).string() << "\n";
    out << "Cache identity: source='" << meshResult.cacheIdentity.sourceIdentifier
        << "' prim='" << meshResult.cacheIdentity.primPath
        << "' subset='" << meshResult.cacheIdentity.subsetName << "'\n";
    out << "Cache source: build_hash=0x" << std::hex << data.cacheSource.buildConfigHash << std::dec
        << " container='" << WideToUtf8Lossy(data.cacheSource.containerFileName) << "'\n";
    out << "Summary: groups=" << groups.size()
        << " voxel_groups=" << voxelGroups
        << " assembly_proxy_groups=" << assemblyProxyGroups
        << " assembly_voxel_groups=" << assemblyVoxelGroups
        << " max_assembly_voxel_depth=" << maxAssemblyVoxelDepth
        << " segments=" << segments.size()
        << " refined_edges=" << refinedEdges
        << " terminal_segments=" << terminalSegments
        << " nodes=" << nodes.size()
        << " internal_nodes=" << internalNodes
        << " segment_leaf_nodes=" << segmentLeafNodes
        << " voxel_leaf_nodes=" << voxelLeafNodes
        << " instance_root_nodes=" << instanceRootNodes
        << " assembly_transforms=" << data.assemblyTransforms.size()
        << " assembly_instances=" << data.assemblyInstances.size()
        << " assembly_max_stack_depth=" << instanceRootMaxStackDepth
        << " lod_levels=" << data.lodLevelRoots.size()
        << " max_depth=" << data.maxDepth
        << " max_traversal_depth=" << data.maxTraversalDepth
        << " triangle_pages=" << data.trianglePageCount
        << " voxel_pages=" << data.voxelPageCount << "\n";
    out << "Errors: group_error_min=" << minGroupError
        << " group_error_max=" << maxGroupError
        << " max_parent_to_own_error_ratio=" << maxParentToOwnErrorRatio << "\n";
    uint32_t rootGroupCount = 0u;
    uint32_t multiParentGroupCount = 0u;
    uint32_t maxParentRefCount = 0u;
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()); ++groupIndex) {
        rootGroupCount += parentRefCounts[groupIndex] == 0u ? 1u : 0u;
        multiParentGroupCount += parentRefCounts[groupIndex] > 1u ? 1u : 0u;
        maxParentRefCount = std::max(maxParentRefCount, parentRefCounts[groupIndex]);
    }
    out << "Parentage: root_groups=" << rootGroupCount
        << " multi_parent_groups=" << multiParentGroupCount
        << " max_parent_ref_count=" << maxParentRefCount << "\n";
    out << "Validation: invalid_segment_ranges=" << invalidSegmentRanges
        << " invalid_refined_groups=" << invalidRefinedGroups
        << " refined_edges_to_lower_depth=" << refinedEdgesToLowerDepth
        << " refined_edges_to_same_or_higher_depth=" << refinedEdgesToSameOrHigherDepth
        << " non_selected_parent_edges=" << nonSelectedParentEdges
        << " finite_group_error_issues=" << finiteGroupErrorIssues
        << " lod_sphere_containment_violations=" << lodSphereContainmentViolations
        << " max_lod_sphere_escape=" << maxLodSphereEscape
        << " invalid_node_kinds=" << invalidNodeKinds
        << " invalid_node_ranges=" << invalidNodeRanges
        << " invalid_leaf_owners=" << invalidLeafOwners
        << " invalid_leaf_segments=" << invalidLeafSegments
        << " invalid_assembly_instances=" << invalidAssemblyInstances
        << " invalid_assembly_targets=" << invalidAssemblyTargets
        << " invalid_assembly_transforms=" << invalidAssemblyTransforms
        << " excessive_assembly_depth=" << excessiveAssemblyDepth
        << " non_finite_node_metrics=" << nonFiniteNodeMetrics
        << " internal_max_error_violations=" << internalMaxErrorViolations
        << " unreachable_nodes=" << unreachableNodes
        << " duplicate_segment_leaf_refs=" << duplicateSegmentLeafRefs << "\n";

    struct DepthIntervalStats {
        uint32_t segments = 0u;
        uint64_t meshlets = 0u;
        float minLower = std::numeric_limits<float>::max();
        float maxLower = 0.0f;
        float minUpper = std::numeric_limits<float>::max();
        float maxUpper = 0.0f;
    };

    std::map<int32_t, DepthIntervalStats> intervalStatsByDepth;
    std::vector<float> thresholdCandidates;
    thresholdCandidates.reserve(groups.size() * 2u + 1u);
    thresholdCandidates.push_back(0.0f);

    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()); ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        if (std::isfinite(group.bounds.error) && group.bounds.error > 0.0f) {
            thresholdCandidates.push_back(group.bounds.error);
        }
        if (group.firstSegment + group.segmentCount > segments.size()) {
            continue;
        }

        for (uint32_t offset = 0; offset < group.segmentCount; ++offset) {
            const ClusterLODGroupSegment& segment = segments[group.firstSegment + offset];
            const float upper = group.bounds.error;
            const float lower = segment.refinedGroup >= 0 && static_cast<uint32_t>(segment.refinedGroup) < groups.size()
                ? groups[static_cast<uint32_t>(segment.refinedGroup)].bounds.error
                : 0.0f;
            if (!std::isfinite(upper) || !std::isfinite(lower) || upper < lower) {
                continue;
            }

            DepthIntervalStats& stats = intervalStatsByDepth[group.depth];
            stats.segments++;
            stats.meshlets += segment.meshletCount;
            stats.minLower = std::min(stats.minLower, lower);
            stats.maxLower = std::max(stats.maxLower, lower);
            stats.minUpper = std::min(stats.minUpper, upper);
            stats.maxUpper = std::max(stats.maxUpper, upper);
        }
    }

    std::sort(thresholdCandidates.begin(), thresholdCandidates.end());
    thresholdCandidates.erase(
        std::unique(
            thresholdCandidates.begin(),
            thresholdCandidates.end(),
            [](float a, float b) {
                const float scale = std::max({ 1.0f, std::fabs(a), std::fabs(b) });
                return std::fabs(a - b) <= scale * 1.0e-5f;
            }),
        thresholdCandidates.end());

    std::vector<float> sweepThresholds;
    sweepThresholds.reserve(thresholdCandidates.size() * 2u);
    for (size_t i = 0; i < thresholdCandidates.size(); ++i) {
        sweepThresholds.push_back(thresholdCandidates[i]);
        if (i + 1u < thresholdCandidates.size()) {
            const float a = thresholdCandidates[i];
            const float b = thresholdCandidates[i + 1u];
            if (b > a) {
                sweepThresholds.push_back(a > 0.0f ? std::sqrt(a * b) : b * 0.5f);
            }
        }
    }

    out << "\nDAG interval coverage by owner depth:\n";
    out << "depth,segments,meshlets,min_child_error,max_child_error,min_owner_error,max_owner_error\n";
    for (const auto& [depth, stats] : intervalStatsByDepth) {
        out << depth << ","
            << stats.segments << ","
            << stats.meshlets << ","
            << (stats.segments != 0u ? stats.minLower : 0.0f) << ","
            << stats.maxLower << ","
            << (stats.segments != 0u ? stats.minUpper : 0.0f) << ","
            << stats.maxUpper << "\n";
    }

    out << "\nDAG threshold sweep (mesh-space interval rule, first 96):\n";
    out << "threshold,total_segments,total_meshlets,dominant_depth,active_depths\n";
    uint32_t sweepRows = 0u;
    int32_t previousDominantDepth = std::numeric_limits<int32_t>::min();
    std::string previousActiveDepths;
    for (float threshold : sweepThresholds) {
        std::map<int32_t, std::pair<uint32_t, uint64_t>> activeByDepth;
        uint32_t totalSegments = 0u;
        uint64_t totalMeshlets = 0u;

        for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()); ++groupIndex) {
            const ClusterLODGroup& group = groups[groupIndex];
            if (!std::isfinite(group.bounds.error) || group.bounds.error <= threshold ||
                group.firstSegment + group.segmentCount > segments.size()) {
                continue;
            }

            for (uint32_t offset = 0; offset < group.segmentCount; ++offset) {
                const ClusterLODGroupSegment& segment = segments[group.firstSegment + offset];
                const float childError = segment.refinedGroup >= 0 && static_cast<uint32_t>(segment.refinedGroup) < groups.size()
                    ? groups[static_cast<uint32_t>(segment.refinedGroup)].bounds.error
                    : 0.0f;
                if (!std::isfinite(childError) || childError > threshold) {
                    continue;
                }

                totalSegments++;
                totalMeshlets += segment.meshletCount;
                auto& depthStats = activeByDepth[group.depth];
                depthStats.first++;
                depthStats.second += segment.meshletCount;
            }
        }

        int32_t dominantDepth = -1;
        uint64_t dominantMeshlets = 0u;
        std::string activeDepths;
        for (const auto& [depth, stats] : activeByDepth) {
            if (!activeDepths.empty()) {
                activeDepths += ";";
            }
            activeDepths += std::to_string(depth) + ":" + std::to_string(stats.first) + "/" + std::to_string(stats.second);
            if (stats.second > dominantMeshlets) {
                dominantMeshlets = stats.second;
                dominantDepth = depth;
            }
        }

        const bool changed = dominantDepth != previousDominantDepth || activeDepths != previousActiveDepths;
        if (!changed) {
            continue;
        }

        out << threshold << ","
            << totalSegments << ","
            << totalMeshlets << ","
            << dominantDepth << ","
            << activeDepths << "\n";

        previousDominantDepth = dominantDepth;
        previousActiveDepths = std::move(activeDepths);
        if (++sweepRows >= 96u) {
            break;
        }
    }

    out << "\nLOD depth summary:\n";
    out << "depth,groups,meshlets,terminal_segments,root_node,root_kind,root_children,root_error,root_lod_radius,range_offset,range_count\n";
    for (uint32_t depth = 0; depth < static_cast<uint32_t>(data.lodLevelRoots.size()); ++depth) {
        const uint32_t rootNode = data.lodLevelRoots[depth];
        const ClusterLODNode* root = rootNode < nodes.size() ? &nodes[rootNode] : nullptr;
        const ClusterLODNodeRangeAlloc range = depth < data.lodNodeRanges.size() ? data.lodNodeRanges[depth] : ClusterLODNodeRangeAlloc{};
        out << depth << ","
            << groupsByDepth[static_cast<int32_t>(depth)] << ","
            << meshletsByDepth[static_cast<int32_t>(depth)] << ","
            << terminalSegmentsByDepth[static_cast<int32_t>(depth)] << ","
            << rootNode << ","
            << (root ? NodeKindName(root->range.isGroup) : "missing") << ","
            << (root && root->range.isGroup == CLOD_NODE_INTERNAL ? root->range.countMinusOne + 1u : 0u) << ","
            << (root ? root->traversalMetric.maxQuadricError : -1.0f) << ","
            << (root ? root->traversalMetric.lodBoundingSphere.w : -1.0f) << ","
            << range.offset << ","
            << range.count << "\n";
    }

    out << "\nTop root children:\n";
    out << "child_index,node_id,kind,child_count,error,lod_x,lod_y,lod_z,lod_radius,cull_x,cull_y,cull_z,cull_radius,owner_group\n";
    if (!nodes.empty() && nodes[0].range.isGroup == CLOD_NODE_INTERNAL) {
        const uint32_t childCount = nodes[0].range.countMinusOne + 1u;
        for (uint32_t child = 0; child < childCount; ++child) {
            const uint32_t nodeIndex = nodes[0].range.indexOrOffset + child;
            if (nodeIndex >= nodes.size()) {
                continue;
            }
            const ClusterLODNode& node = nodes[nodeIndex];
            out << child << ","
                << nodeIndex << ","
                << NodeKindName(node.range.isGroup) << ","
                << (node.range.isGroup == CLOD_NODE_INTERNAL ? node.range.countMinusOne + 1u : 0u) << ","
                << node.traversalMetric.maxQuadricError << ","
                << node.traversalMetric.lodBoundingSphere.x << ","
                << node.traversalMetric.lodBoundingSphere.y << ","
                << node.traversalMetric.lodBoundingSphere.z << ","
                << node.traversalMetric.lodBoundingSphere.w << ","
                << node.traversalMetric.cullingSphere.x << ","
                << node.traversalMetric.cullingSphere.y << ","
                << node.traversalMetric.cullingSphere.z << ","
                << node.traversalMetric.cullingSphere.w << ","
                << (node.range.isGroup == CLOD_NODE_INTERNAL ? -1 : static_cast<int32_t>(node.range.ownerGroupId)) << "\n";
        }
    }

    out << "\nAssembly voxel groups (first 256):\n";
    out << "group,depth,parent,flags,error,center_x,center_y,center_z,radius,segments,page_base,page_count,leaf_refs\n";
    uint32_t assemblyVoxelRows = 0u;
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()) && assemblyVoxelRows < 256u; ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        if ((group.flags & CLOD_GROUP_FLAG_IS_ASSEMBLY_VOXEL) == 0u) {
            continue;
        }
        out << groupIndex << ","
            << group.depth << ","
            << group.parentGroupId << ",0x" << std::hex << group.flags << std::dec << ","
            << group.bounds.error << ","
            << group.bounds.center[0] << ","
            << group.bounds.center[1] << ","
            << group.bounds.center[2] << ","
            << group.bounds.radius << ","
            << group.segmentCount << ","
            << group.pageMapBase << ","
            << group.pageCount << ","
            << groupLeafRefs[groupIndex] << "\n";
        ++assemblyVoxelRows;
    }

    out << "\nAssembly voxel segments (first 512):\n";
    out << "segment,owner_group,owner_depth,refined_group,refined_depth,meshlets,page,first_meshlet,bounds_x,bounds_y,bounds_z,bounds_radius\n";
    uint32_t assemblySegmentRows = 0u;
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()) && assemblySegmentRows < 512u; ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        if ((group.flags & CLOD_GROUP_FLAG_IS_ASSEMBLY_VOXEL) == 0u ||
            group.firstSegment + group.segmentCount > segments.size()) {
            continue;
        }
        for (uint32_t offset = 0; offset < group.segmentCount && assemblySegmentRows < 512u; ++offset) {
            const uint32_t segmentIndex = group.firstSegment + offset;
            const ClusterLODGroupSegment& segment = segments[segmentIndex];
            const int32_t refinedDepth = segment.refinedGroup >= 0 && static_cast<uint32_t>(segment.refinedGroup) < groups.size()
                ? groups[static_cast<uint32_t>(segment.refinedGroup)].depth
                : -1;
            const DirectX::XMFLOAT4 bounds = segmentIndex < data.segmentBounds.size()
                ? data.segmentBounds[segmentIndex].sphere
                : DirectX::XMFLOAT4{};
            out << segmentIndex << ","
                << groupIndex << ","
                << group.depth << ","
                << segment.refinedGroup << ","
                << refinedDepth << ","
                << segment.meshletCount << ","
                << segment.pageIndex << ","
                << segment.firstMeshletInPage << ","
                << bounds.x << ","
                << bounds.y << ","
                << bounds.z << ","
                << bounds.w << "\n";
            ++assemblySegmentRows;
        }
    }

    out << "\nAssembly instances:\n";
    out << "instance,target_root,target_kind,transform,flags,stack_depth,node_refs,translation_x,translation_y,translation_z,bounds_x,bounds_y,bounds_z,bounds_radius\n";
    std::vector<uint32_t> assemblyNodeRefs(data.assemblyInstances.size(), 0u);
    for (const ClusterLODNode& node : nodes) {
        if (node.range.isGroup == CLOD_NODE_INSTANCE_ROOT && node.range.indexOrOffset < assemblyNodeRefs.size()) {
            assemblyNodeRefs[node.range.indexOrOffset]++;
        }
    }
    for (uint32_t instanceIndex = 0; instanceIndex < static_cast<uint32_t>(data.assemblyInstances.size()); ++instanceIndex) {
        const ClusterLODAssemblyInstance& instance = data.assemblyInstances[instanceIndex];
        const ClusterLODNode* target = instance.targetRootNode < nodes.size() ? &nodes[instance.targetRootNode] : nullptr;
        const ClusterLODAssemblyTransform* transform =
            instance.transformIndex != CLOD_ASSEMBLY_TRANSFORM_SENTINEL &&
                instance.transformIndex < data.assemblyTransforms.size()
            ? &data.assemblyTransforms[instance.transformIndex]
            : nullptr;
        out << instanceIndex << ","
            << instance.targetRootNode << ","
            << (target ? NodeKindName(target->range.isGroup) : "missing") << ","
            << (instance.transformIndex == CLOD_ASSEMBLY_TRANSFORM_SENTINEL ? -1 : static_cast<int32_t>(instance.transformIndex)) << ",0x"
            << std::hex << instance.flags << std::dec << ","
            << instance.stackDepth << ","
            << assemblyNodeRefs[instanceIndex] << ","
            << (transform ? transform->row0.w : 0.0f) << ","
            << (transform ? transform->row1.w : 0.0f) << ","
            << (transform ? transform->row2.w : 0.0f) << ","
            << (target ? target->traversalMetric.cullingSphere.x : 0.0f) << ","
            << (target ? target->traversalMetric.cullingSphere.y : 0.0f) << ","
            << (target ? target->traversalMetric.cullingSphere.z : 0.0f) << ","
            << (target ? target->traversalMetric.cullingSphere.w : 0.0f) << "\n";
    }

    out << "\nAssembly transforms (first 128):\n";
    out << "transform,row0_x,row0_y,row0_z,row0_w,row1_x,row1_y,row1_z,row1_w,row2_x,row2_y,row2_z,row2_w\n";
    for (uint32_t transformIndex = 0; transformIndex < static_cast<uint32_t>(data.assemblyTransforms.size()) && transformIndex < 128u; ++transformIndex) {
        const ClusterLODAssemblyTransform& transform = data.assemblyTransforms[transformIndex];
        out << transformIndex << ","
            << transform.row0.x << "," << transform.row0.y << "," << transform.row0.z << "," << transform.row0.w << ","
            << transform.row1.x << "," << transform.row1.y << "," << transform.row1.z << "," << transform.row1.w << ","
            << transform.row2.x << "," << transform.row2.y << "," << transform.row2.z << "," << transform.row2.w << "\n";
    }

    out << "\nRoot groups:\n";
    out << "group,depth,error,segments,terminal_segments,meshlets,leaf_refs,page_base,page_count\n";
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()); ++groupIndex) {
        if (parentRefCounts[groupIndex] != 0u) {
            continue;
        }
        const ClusterLODGroup& group = groups[groupIndex];
        out << groupIndex << ","
            << group.depth << ","
            << group.bounds.error << ","
            << group.segmentCount << ","
            << group.terminalSegmentCount << ","
            << group.meshletCount << ","
            << groupLeafRefs[groupIndex] << ","
            << group.pageMapBase << ","
            << group.pageCount << "\n";
    }

    out << "\nSuspicious groups (first 128):\n";
    out << "group,depth,flags,parent_refs,selected_parent,max_direct_parent_error,max_parent_error,own_error,parent_to_own_ratio,segments,terminal_segments,meshlets,page_base,page_count,leaf_refs\n";
    uint32_t suspiciousWritten = 0;
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()) && suspiciousWritten < 128u; ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        const float ratio = group.bounds.error > 0.0f && group.maxParentError < std::numeric_limits<float>::max() * 0.5f
            ? group.maxParentError / group.bounds.error
            : 0.0f;
        const bool suspicious =
            ratio > 16.0f ||
            group.parentGroupId < 0 ||
            group.segmentCount == 0u ||
            groupLeafRefs[groupIndex] == 0u ||
            !std::isfinite(group.bounds.error);
        if (!suspicious) {
            continue;
        }
        out << groupIndex << ","
            << group.depth << ",0x" << std::hex << group.flags << std::dec << ","
            << parentRefCounts[groupIndex] << ","
            << group.parentGroupId << ","
            << maxDirectParentError[groupIndex] << ","
            << group.maxParentError << ","
            << group.bounds.error << ","
            << ratio << ","
            << group.segmentCount << ","
            << group.terminalSegmentCount << ","
            << group.meshletCount << ","
            << group.pageMapBase << ","
            << group.pageCount << ","
            << groupLeafRefs[groupIndex] << "\n";
        suspiciousWritten++;
    }

    out << "\nSuspicious segments (first 128):\n";
    out << "segment,owner_group,owner_depth,refined_group,refined_depth,meshlets,page,first_meshlet,leaf_refs\n";
    uint32_t segmentRows = 0;
    for (uint32_t groupIndex = 0; groupIndex < static_cast<uint32_t>(groups.size()) && segmentRows < 128u; ++groupIndex) {
        const ClusterLODGroup& group = groups[groupIndex];
        if (group.firstSegment + group.segmentCount > segments.size()) {
            continue;
        }
        for (uint32_t offset = 0; offset < group.segmentCount && segmentRows < 128u; ++offset) {
            const uint32_t segmentIndex = group.firstSegment + offset;
            const ClusterLODGroupSegment& segment = segments[segmentIndex];
            const int32_t refinedDepth = segment.refinedGroup >= 0 && static_cast<uint32_t>(segment.refinedGroup) < groups.size()
                ? groups[static_cast<uint32_t>(segment.refinedGroup)].depth
                : -1;
            const uint32_t leafRefs = segmentLeafRefs[segmentIndex];
            const bool suspicious =
                segment.refinedGroup >= static_cast<int32_t>(groups.size()) ||
                (segment.refinedGroup >= 0 && refinedDepth >= group.depth) ||
                leafRefs != 1u ||
                segment.meshletCount == 0u;
            if (!suspicious) {
                continue;
            }
            out << segmentIndex << ","
                << groupIndex << ","
                << group.depth << ","
                << segment.refinedGroup << ","
                << refinedDepth << ","
                << segment.meshletCount << ","
                << segment.pageIndex << ","
                << segment.firstMeshletInPage << ","
                << leafRefs << "\n";
            segmentRows++;
        }
    }

    out << "\n\n";
}

static bool TryConsumeOption(const std::string& arg) {
    if (arg == "--debug") {
        spdlog::set_level(spdlog::level::debug);
        spdlog::flush_on(spdlog::level::debug);
        return true;
    }

    constexpr const char* reportPrefix = "--clod-report=";
    constexpr const char* tessellationPrefix = "--usd-tessellation-factor=";
    constexpr const char* modePrefix = "--clod-coverage-preservation-mode=";
    constexpr const char* gridPrefix = "--clod-voxel-grid=";
    constexpr const char* minResPrefix = "--clod-voxel-min-res=";
    constexpr const char* raysPrefix = "--clod-voxel-rays=";
    constexpr const char* scalePrefix = "--clod-voxel-scale=";
    constexpr const char* retriesPrefix = "--clod-voxel-retries=";
    constexpr const char* growthPrefix = "--clod-voxel-growth=";
    constexpr const char* biasPrefix = "--clod-voxel-acceptance-bias=";
    constexpr const char* opacityPrefix = "--clod-voxel-opacity-threshold=";
    constexpr const char* pruningPrefix = "--clod-voxel-pruning=";
    constexpr const char* disableSloppyPrefix = "--clod-disable-sloppy-fallback=";
    constexpr const char* sloppyFactorPrefix = "--clod-sloppy-error-factor=";
    constexpr const char* assetOverridesPrefix = "--asset-overrides=";

    const std::string assetOverridesPrefixString(assetOverridesPrefix);
    if (arg.rfind(assetOverridesPrefixString, 0) == 0) {
        g_assetOverridesConfig = arg.substr(assetOverridesPrefixString.size());
        return true;
    }

    auto consumeValue = [&arg](const char* prefix, const char* envName) -> bool {
        const std::string prefixString(prefix);
        if (arg.rfind(prefixString, 0) != 0) {
            return false;
        }
        SetProcessEnvironment(envName, arg.substr(prefixString.size()));
        return true;
    };

    const std::string reportPrefixString(reportPrefix);
    if (arg.rfind(reportPrefixString, 0) == 0) {
        g_reportEnabled = true;
        g_reportPath = arg.substr(reportPrefixString.size());
        return true;
    }

    const std::string tessellationPrefixString(tessellationPrefix);
    if (arg.rfind(tessellationPrefixString, 0) == 0) {
        char* end = nullptr;
        const unsigned long value = std::strtoul(arg.c_str() + tessellationPrefixString.size(), &end, 10);
        if (end != arg.c_str() + tessellationPrefixString.size() && value > 0ul) {
            g_usdTessellationFactor = static_cast<uint32_t>(std::min<unsigned long>(value, std::numeric_limits<uint32_t>::max()));
        }
        return true;
    }

    return consumeValue(modePrefix, "BASICRENDERER_CLOD_COVERAGE_PRESERVATION_MODE") ||
        consumeValue(gridPrefix, "BASICRENDERER_CLOD_VOXEL_GRID") ||
        consumeValue(minResPrefix, "BASICRENDERER_CLOD_VOXEL_MIN_RES") ||
        consumeValue(raysPrefix, "BASICRENDERER_CLOD_VOXEL_RAYS") ||
        consumeValue(scalePrefix, "BASICRENDERER_CLOD_VOXEL_SCALE") ||
        consumeValue(retriesPrefix, "BASICRENDERER_CLOD_VOXEL_RETRIES") ||
        consumeValue(growthPrefix, "BASICRENDERER_CLOD_VOXEL_GROWTH") ||
        consumeValue(biasPrefix, "BASICRENDERER_CLOD_VOXEL_ACCEPTANCE_BIAS") ||
        consumeValue(opacityPrefix, "BASICRENDERER_CLOD_VOXEL_OPACITY_THRESHOLD") ||
        consumeValue(pruningPrefix, "BASICRENDERER_CLOD_VOXEL_PRUNING") ||
        consumeValue(disableSloppyPrefix, "BASICRENDERER_CLOD_DISABLE_SLOPPY_FALLBACK") ||
        consumeValue(sloppyFactorPrefix, "BASICRENDERER_CLOD_SLOPPY_ERROR_FACTOR");
}

// Processing

static bool ProcessFile(const fs::path& path) {
    ZoneScopedN("CLodCacheTool::ProcessFile");
    auto canonical = fs::weakly_canonical(path);
    auto pathStr   = canonical.string();
    const auto sourceOverride = g_sourceIdentifierOverrides.find(CanonicalPathKey(canonical));
    const std::string sourceIdentifier = sourceOverride != g_sourceIdentifierOverrides.end()
        ? sourceOverride->second
        : pathStr;
    auto fmt       = DetectFormat(canonical);

    if (fmt == AssetFormat::USD && sourceOverride != g_sourceIdentifierOverrides.end()) {
        if (auto manifest = USDMaterialCache::LoadAssemblyMaterialManifest(sourceIdentifier);
            manifest && !manifest->empty()) {
            const bool complete = std::ranges::all_of(*manifest, [](const auto& entry) {
                auto prebuilt = CLodCacheLoader::TryLoadPrebuilt(entry.identity);
                return prebuilt.has_value() && !prebuilt->assemblyInstances.empty();
            });
            if (complete) {
                spdlog::info(
                    "[USD] Skipping object override with valid material assembly cache: source='{}' buckets={}",
                    sourceIdentifier,
                    manifest->size());
                return true;
            }
            spdlog::info(
                "[USD] Object override material assembly cache is incomplete; rebuilding source='{}'",
                sourceIdentifier);
        }
    }

    spdlog::info("---------------------------------------------------");
    spdlog::info("[{}] Processing: {}", FormatName(fmt), pathStr);
    spdlog::info("  File size: {} bytes", fs::file_size(canonical));
    TracyPlot("CLOD.Tool.FileBytes", static_cast<int64_t>(fs::file_size(canonical)));

    auto t0 = std::chrono::steady_clock::now();

    try {
        switch (fmt) {
        case AssetFormat::USD: {
            ZoneScopedN("CLodCacheTool::ProcessFile::USD");
            spdlog::info("  Opening USD stage...");
            pxr::UsdStageRefPtr stage;
            {
                ZoneScopedN("CLodCacheTool::USD::OpenStage");
                stage = pxr::UsdStage::Open(pathStr);
            }
            const uint64_t sourceTriangles = CountUsdStageSourceTriangles(stage);
            spdlog::info("  USD source geometry: triangles={} (scene instances included)", sourceTriangles);
            WriteUsdAssemblyReport(canonical, "USD source", stage);
            USDGeometryExtractor::ExtractOptions extractOptions{};
            extractOptions.retainClusterLODArtifacts = true;
            // Material-bucket assembly baking needs retained child artifacts even when
            // each child already has a disk cache.
            extractOptions.skipCachedClusterLODMeshBuilds = false;
            extractOptions.buildPointInstancerAssemblyCaches = false;
            // The material-bucket whole-asset builder in USDLoader owns this
            // format because it also expands UsdSkel and DynamicWind metadata.
            // The geometry-only extractor cannot safely publish a manifest for
            // skinned assets.
            extractOptions.buildWholeAssetAssemblyCaches = false;
            extractOptions.importSkinningAsRigidBindPose = true;
            USDGeometryExtractor::StageExtractionResult result;
            {
                ZoneScopedN("CLodCacheTool::USD::ExtractAllFromStage");
                result = USDGeometryExtractor::ExtractAllFromStage(stage, sourceIdentifier, g_usdTessellationFactor, extractOptions);
            }
            spdlog::info("  USD result: meshes={}, submeshes={}, caches_built={}, source_triangles={}",
                         result.meshesProcessed,
                         result.submeshesProcessed,
                         result.cachesBuilt,
                         sourceTriangles);
            for (size_t i = 0; i < result.submeshes.size(); ++i) {
                WriteClusterLODReport(canonical, "USD submesh " + std::to_string(i), result.submeshes[i]);
            }
            if (result.meshesProcessed == 0)
                spdlog::warn("  No UsdGeomMesh prims found in stage!");
            break;
        }
        case AssetFormat::GlTF: {
            ZoneScopedN("CLodCacheTool::ProcessFile::GlTF");
            spdlog::info("  Loading glTF...");
            auto result = GlTFGeometryExtractor::ExtractAll(pathStr);
            uint64_t extractedTriangles = 0;
            for (const auto& primitive : result.primitives) {
                extractedTriangles += primitive.result.ingest.GetIndices().size() / 3ull;
            }
            spdlog::info("  glTF result: primitives extracted: {}, extracted_triangles={}",
                         result.primitives.size(),
                         extractedTriangles);
            for (const auto& primitive : result.primitives) {
                WriteClusterLODReport(
                    canonical,
                    "glTF mesh " + std::to_string(primitive.meshIndex) + " primitive " + std::to_string(primitive.primitiveIndex),
                    primitive.result);
            }
            if (result.primitives.empty())
                spdlog::warn("  No primitives found in glTF file!");
            break;
        }
        case AssetFormat::Nif: {
            ZoneScopedN("CLodCacheTool::ProcessFile::NIF");
            spdlog::info("  Converting NIF through BRNifly...");
            std::string errorMessage;
            std::optional<BRNiflyClient::UsdAssetPackage> package;
            {
                ZoneScopedN("CLodCacheTool::NIF::ConvertNifToUsd");
                package = BRNiflyClient::ConvertNifToUsd(pathStr, {}, &errorMessage);
            }
            if (!package) {
                spdlog::error("  BRNifly conversion failed: {}", errorMessage);
                return false;
            }

            for (const auto& diagnostic : package->diagnostics) {
                if (diagnostic.level == "warning")
                    spdlog::warn("  BRNifly: {}", diagnostic.message);
                else if (diagnostic.level == "error")
                    spdlog::error("  BRNifly: {}", diagnostic.message);
                else
                    spdlog::info("  BRNifly: {}", diagnostic.message);
            }

            auto layer = pxr::SdfLayer::CreateAnonymous("brnifly_clod.usda");
            if (!layer || !layer->ImportFromString(package->rootLayerText)) {
                spdlog::error("  Failed to import BRNifly USDA payload.");
                return false;
            }
            auto stage = pxr::UsdStage::Open(layer);
            if (!stage) {
                spdlog::error("  Failed to open BRNifly USDA stage.");
                return false;
            }

            const uint64_t sourceTriangles = CountUsdStageSourceTriangles(stage);
            spdlog::info("  NIF/USD source geometry: triangles={} (scene instances included)", sourceTriangles);
            WriteUsdAssemblyReport(canonical, "NIF/USD source", stage);
            USDGeometryExtractor::ExtractOptions extractOptions{};
            extractOptions.retainClusterLODArtifacts = true;
            extractOptions.skipCachedClusterLODMeshBuilds = false;
            extractOptions.buildPointInstancerAssemblyCaches = false;
            extractOptions.buildWholeAssetAssemblyCaches = true;
            extractOptions.importSkinningAsRigidBindPose = true;
            USDGeometryExtractor::StageExtractionResult result;
            {
                ZoneScopedN("CLodCacheTool::NIF::ExtractAllFromStage");
                result = USDGeometryExtractor::ExtractAllFromStage(stage, package->sourceIdentifier, g_usdTessellationFactor, extractOptions);
            }
            spdlog::info("  NIF/USD result: meshes={}, submeshes={}, caches_built={}, source_triangles={}",
                         result.meshesProcessed,
                         result.submeshesProcessed,
                         result.cachesBuilt,
                         sourceTriangles);
            for (size_t i = 0; i < result.submeshes.size(); ++i) {
                WriteClusterLODReport(canonical, "NIF/USD submesh " + std::to_string(i), result.submeshes[i]);
            }
            if (result.meshesProcessed == 0)
                spdlog::warn("  No UsdGeomMesh prims found in converted NIF stage!");
            break;
        }
        case AssetFormat::Assimp: {
            ZoneScopedN("CLodCacheTool::ProcessFile::Assimp");
            spdlog::info("  Loading via Assimp...");
            auto result = AssimpGeometryExtractor::ExtractAll(pathStr);
            uint64_t extractedTriangles = 0;
            for (const auto& mesh : result.meshes) {
                extractedTriangles += mesh.result.ingest.GetIndices().size() / 3ull;
            }
            spdlog::info("  Assimp result: meshes extracted: {}, extracted_triangles={}",
                         result.meshes.size(),
                         extractedTriangles);
            for (const auto& mesh : result.meshes) {
                WriteClusterLODReport(canonical, "Assimp mesh " + std::to_string(mesh.meshIndex), mesh.result);
            }
            if (result.meshes.empty())
                spdlog::warn("  No meshes found via Assimp!");
            break;
        }
        }
    } catch (const std::exception& ex) {
        spdlog::error("  EXCEPTION: {}", ex.what());
        return false;
    } catch (...) {
        spdlog::error("  UNKNOWN EXCEPTION (non-std::exception)");
        return false;
    }

    auto t1 = std::chrono::steady_clock::now();
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count();
    spdlog::info("  Elapsed: {} ms", ms);
    return true;
}

int main(int argc, char* argv[]) {
    ZoneScopedN("CLodCacheTool::main");
    
    spdlog::set_default_logger(spdlog::stdout_color_mt("CLodCacheTool"));
    spdlog::set_level(spdlog::level::info);
    spdlog::set_pattern("[%H:%M:%S.%e] [%^%l%$] %v");
    spdlog::flush_on(spdlog::level::info);

    spdlog::info("CLodCacheTool starting  (argc={})", argc);
    spdlog::info("Working directory: {}", fs::current_path().string());

    {
        auto cacheRoot = GetCacheRootPath();
        spdlog::info("Cache root directory: {}", cacheRoot.string());
        if (fs::exists(cacheRoot))
            spdlog::info("  (cache root already exists)");
        else
            spdlog::info("  (cache root does NOT exist yet - will be created on first save)");
    }

    if (argc < 2) {
        spdlog::error("No arguments provided.");
            std::cerr << "Usage: CLodCacheTool [--asset-overrides=config.json] [--clod-report=path] [--usd-tessellation-factor=N] [--clod-coverage-preservation-mode=none|prioritizeEdges|voxel] <file1|dir1> [file2|dir2 ...]\n";
        return 1;
    }

    for (int i = 1; i < argc; ++i)
        spdlog::info("  argv[{}] = \"{}\"", i, argv[i]);

    // Initialise task scheduler
    spdlog::info("Initialising task scheduler...");
    auto& scheduler = br::TaskSchedulerManager::GetInstance();
    scheduler.Initialize();
    spdlog::info("Task scheduler ready.");

    // Gather files
    std::vector<fs::path> files;
    {
        ZoneScopedN("CLodCacheTool::GatherFiles");
        for (int i = 1; i < argc; ++i) {
        const std::string arg(argv[i]);
        if (TryConsumeOption(arg)) {
            spdlog::info("Consumed option: {}", arg);
            continue;
        }

        fs::path p(argv[i]);
        if (!fs::exists(p)) {
            spdlog::warn("Skipping non-existent path: {}", argv[i]);
            continue;
        }
        if (fs::is_directory(p)) {
            spdlog::info("Scanning directory: {}", fs::weakly_canonical(p).string());
            size_t before = files.size();
            for (auto& entry : fs::recursive_directory_iterator(p)) {
                if (entry.is_regular_file())
                    files.push_back(entry.path());
            }
            spdlog::info("  Found {} file(s) in directory.", files.size() - before);
        } else {
            files.push_back(p);
        }
        }

        if (!g_assetOverridesConfig.empty()) {
            try {
                std::ifstream input(g_assetOverridesConfig);
                if (!input)
                    throw std::runtime_error("could not open asset override config");
                const auto document = nlohmann::json::parse(input);
                const auto overridesIt = document.find("overrides");
                if (overridesIt == document.end())
                    throw std::runtime_error("asset override config is missing 'overrides'");

                std::vector<std::string> replacements;
                auto addReplacement = [&](const nlohmann::json& value) {
                    if (value.is_string())
                        replacements.push_back(value.get<std::string>());
                    else if (value.is_object()) {
                        const std::string replacement = value.value("replacement", std::string{});
                        if (!replacement.empty())
                            replacements.push_back(replacement);
                    }
                };
                if (overridesIt->is_object()) {
                    for (const auto& [_, value] : overridesIt->items())
                        addReplacement(value);
                } else if (overridesIt->is_array()) {
                    for (const auto& value : *overridesIt)
                        addReplacement(value);
                } else {
                    throw std::runtime_error("'overrides' must be an object or array");
                }

                std::vector<fs::path> roots;
                if (const char* dataPath = std::getenv("SARP_DATA_PATH"); dataPath && *dataPath)
                    roots.emplace_back(dataPath);
                if (const auto rootsIt = document.find("assetRoots"); rootsIt != document.end() && rootsIt->is_array()) {
                    for (const auto& rootValue : *rootsIt) {
                        if (!rootValue.is_string())
                            continue;
                        fs::path root(rootValue.get<std::string>());
                        if (root.is_relative())
                            root = g_assetOverridesConfig.parent_path() / root;
                        roots.push_back(std::move(root));
                    }
                }
                roots.push_back(g_assetOverridesConfig.parent_path());
                roots.push_back(g_assetOverridesConfig.parent_path().parent_path());
                roots.push_back(fs::current_path());
				// Match the renderer host's asset-root behavior: when the tool runs
				// from <mod>/SKSE/Plugins/SARP/Renderer, override assets may live at
				// the mod root beside SKSE rather than beside the executable.
				for (fs::path ancestor = fs::current_path(); ancestor.has_parent_path();) {
					std::string name = ToLower(ancestor.filename().string());
					if (name == "skse") {
						roots.push_back(ancestor.parent_path());
						break;
					}
					const fs::path parent = ancestor.parent_path();
					if (parent == ancestor) {
						break;
					}
					ancestor = parent;
				}

                std::unordered_set<std::string> addedPaths;
                for (const std::string& replacementText : replacements) {
                    const std::string logicalPath = NormalizeLogicalAssetPath(replacementText);
                    fs::path relativePath(logicalPath);
                    fs::path resolved;
                    for (const fs::path& root : roots) {
                        const fs::path candidate = root / relativePath;
                        if (fs::exists(candidate)) {
                            resolved = candidate;
                            break;
                        }
                    }
                    if (resolved.empty()) {
                        spdlog::warn("Asset override replacement was not found: {}", logicalPath);
                        continue;
                    }
                    const std::string pathKey = CanonicalPathKey(resolved);
                    g_sourceIdentifierOverrides.insert_or_assign(pathKey, logicalPath);
                    if (addedPaths.insert(pathKey).second) {
                        files.push_back(std::move(resolved));
                        spdlog::info("Asset override cache input: logical='{}' resolved='{}'", logicalPath, files.back().string());
                    }
                }
            } catch (const std::exception& error) {
                spdlog::error("Failed to load asset overrides '{}': {}", g_assetOverridesConfig.string(), error.what());
            }
        }
    }

    if (files.empty()) {
        spdlog::error("No input files found after scanning arguments.");
        scheduler.Cleanup();
        return 1;
    }

    spdlog::info("Gathered {} file(s):", files.size());
    for (size_t i = 0; i < files.size(); ++i) {
        auto ext = ToLower(files[i].extension().string());
        auto fmt = DetectFormat(files[i]);
        spdlog::info("  [{}] ({}) {}", i, FormatName(fmt), files[i].string());
    }

    auto totalT0 = std::chrono::steady_clock::now();

    std::atomic<int> successes{ 0 };
    std::atomic<int> failures{ 0 };

    {
        ZoneScopedN("CLodCacheTool::ProcessFiles");
        TracyPlot("CLOD.Tool.Files", static_cast<int64_t>(files.size()));
        scheduler.ParallelFor("CLodCacheTool::ProcessOverrideAssets", files.size(), [&](std::size_t index) {
            if (ProcessFile(files[index]))
                successes.fetch_add(1, std::memory_order_relaxed);
            else
                failures.fetch_add(1, std::memory_order_relaxed);
            FrameMarkNamed("CLodCacheToolFile");
        });
    }

    auto totalT1 = std::chrono::steady_clock::now();
    auto totalMs = std::chrono::duration_cast<std::chrono::milliseconds>(totalT1 - totalT0).count();

    spdlog::info("=====================================================");
    spdlog::info("Done.  {} succeeded, {} failed.  Total time: {} ms", successes.load(), failures.load(), totalMs);

    // Report cache directory contents
    {
        auto cacheRoot = GetCacheRootPath();
        if (fs::exists(cacheRoot)) {
            size_t cacheFileCount = 0;
            uintmax_t cacheBytes = 0;
            for (auto& entry : fs::recursive_directory_iterator(cacheRoot)) {
                if (entry.is_regular_file()) {
                    ++cacheFileCount;
                    cacheBytes += entry.file_size();
                }
            }
            spdlog::info("Cache directory: {} file(s), {:.2f} MB total",
                         cacheFileCount, cacheBytes / (1024.0 * 1024.0));
        } else {
            spdlog::warn("Cache directory was NOT created - no caches were written.");
        }
    }

    scheduler.Cleanup();
    return failures.load() > 0 ? 1 : 0;
}
