if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SyncTbbRuntime.cmake requires SOURCE_DIR.")
endif()

if(NOT DEFINED DESTINATION_DIR)
    message(FATAL_ERROR "SyncTbbRuntime.cmake requires DESTINATION_DIR.")
endif()

if(NOT DEFINED CONFIG)
    set(CONFIG "")
endif()

file(MAKE_DIRECTORY "${DESTINATION_DIR}")

if(CONFIG STREQUAL "Debug")
    if(EXISTS "${SOURCE_DIR}/tbb_debug.dll")
        file(COPY "${SOURCE_DIR}/tbb_debug.dll" DESTINATION "${DESTINATION_DIR}")
    elseif(EXISTS "${SOURCE_DIR}/tbb.dll")
        configure_file("${SOURCE_DIR}/tbb.dll" "${DESTINATION_DIR}/tbb_debug.dll" COPYONLY)
    else()
        message(FATAL_ERROR "Neither tbb_debug.dll nor tbb.dll was found in ${SOURCE_DIR}.")
    endif()
else()
    if(EXISTS "${SOURCE_DIR}/tbb.dll")
        file(COPY "${SOURCE_DIR}/tbb.dll" DESTINATION "${DESTINATION_DIR}")
    else()
        message(FATAL_ERROR "tbb.dll was not found in ${SOURCE_DIR}.")
    endif()
endif()
