#pragma once

enum OutputType {
	COLOR = 0,
	NORMAL = 1,
	ALBEDO = 2,
	METALLIC = 3,
	ROUGHNESS = 4,
	EMISSIVE = 5,
	AO = 6,
	DEPTH = 7,
	OUTPUT_DIFFUSE_IBL = 8,
	OUTPUT_SPECULAR_IBL = 9,
	MESHLETS = 10,
	MODEL_NORMAL = 11,
	LIGHT_CLUSTER_ID = 12,
	CLUSTERED_LIGHT_COUNT = 13,
	MOTION_VECTORS = 14,
	SW_RASTER = 15,
	TRANSPARENT_NODE_COUNT = 16,
	TRANSPARENT_DEPTH_COMPLEXITY = 17,
	TRANSPARENT_RESOLVED_SAMPLE_COUNT = 18,
	REYES_GEOMETRY_PATH = 19,
	VSM_PREFERRED_CLIPMAP = 20,
	VSM_SAMPLED_CLIPMAP = 21,
	VSM_PAGE_STATE = 22,
	VSM_PHYSICAL_PAGE = 23,
	VSM_RERENDERED_THIS_FRAME = 24,
	TRANSPARENT_VBOIT_TRANSMITTANCE = 25,
	TRANSPARENT_VBOIT_COVERAGE = 26,
	TRANSPARENT_VBOIT_ZERO_SLICE = 27,
	TRANSPARENT_VBOIT_VIRTUAL_SLICE_COUNT = 28,
	TRANSPARENT_VBOIT_PHYSICAL_SLICE_COUNT = 29,
	TRANSPARENT_VBOIT_FITTED_VIRTUAL_SLICE_COUNT = 30,
	TRANSPARENT_VBOIT_OCCUPIED_VIRTUAL_SLICE_COUNT = 31,
	TRANSPARENT_VBOIT_DEPTH_DISTRIBUTION_EXPONENT = 32,
	MATERIAL_SELECTED_MIP = 33,
	VOXEL_GEOMETRY_PATH = 34,
	GEOMETRY_GROUP = 35,
	PARALLAX_PIXELS = 36,
	TERRAIN_RVT_HIT = 37,
	TERRAIN_RVT_REQUESTED_MIP = 38,
	TERRAIN_RVT_RESIDENT_MIP = 39,
	TERRAIN_RVT_VIRTUAL_PAGE = 40,
	TERRAIN_RVT_PHYSICAL_PAGE = 41,
	TERRAIN_RVT_PAGE_UV = 42,
	TERRAIN_RVT_ATLAS_POOL = 43,
	TERRAIN_RVT_ATLAS_UV = 44,
	TERRAIN_RVT_SAMPLED_ALBEDO = 45,
	TERRAIN_RVT_FALLBACK_REASON = 46,
	TERRAIN_RVT_OWNER_PAGE = 47,
	TERRAIN_RVT_PAGE_DELTA = 48,
	TERRAIN_RVT_PHYSICAL_TILE_UV = 49,
	TERRAIN_RVT_SAMPLED_NORMAL = 50,
	TERRAIN_RVT_SAMPLED_MATERIAL = 51,
	TERRAIN_RVT_SAMPLED_ALBEDO_POINT = 52,
	TERRAIN_RVT_HEIGHT_SCALE = 53,
	TERRAIN_GEOMETRIC_HEIGHT = 54,
	TERRAIN_GEOMETRIC_HEIGHT_SLOPE = 55,
	TERRAIN_DOMINANT_LAYER = 56,
	TERRAIN_DOMINANT_WEIGHT = 57,
	TERRAIN_TEXTURE_UV = 58,
	TERRAIN_TEXTURE_SEAM = 59,
	TERRAIN_PAINT_GRID = 60,
	MATERIAL_UV = 61,
	MATERIAL_UV_DERIVATIVE = 62,
	REYES_SOURCE_BARYCENTRICS = 63,
	MATERIAL_EVAL_FEATURES = 64,
	TERRAIN_GRASS_OVERLAY = 65,
	CLOD_ASSEMBLY_VOXEL_INHERITANCE = 66,
	CLOD_ASSEMBLY_PARTS = 67,
};

inline std::vector<std::string> OutputTypeNames = {
	"Color",
	"Normal",
	"Albedo",
	"Metallic",
	"Roughness",
	"Emissive",
	"Ambient Occlusion",
	"Depth",
	"Diffuse IBL",
	"Specular IBL",
	"Meshlets",
	"Model Normal",
	"Light Cluster ID",
	"Clustered Light Count",
	"Motion Vectors",
	"SW Raster",
	"Transparent Node Count",
	"Transparent Depth Complexity",
	"Transparent Resolved Sample Count",
	"Reyes Geometry Path",
	"VSM Preferred Clipmap",
	"VSM Sampled Clipmap",
	"VSM Page State",
	"VSM Physical Page",
	"VSM Re-rendered This Frame",
	"Transparent VBOIT Transmittance",
	"Transparent VBOIT Coverage",
	"Transparent VBOIT Zero Slice",
	"Transparent VBOIT Virtual Slice Count",
	"Transparent VBOIT Physical Slice Count",
	"Transparent VBOIT Fitted Virtual Slice Count",
	"Transparent VBOIT Occupied Virtual Slice Count",
	"Transparent VBOIT Depth Distribution Exponent",
	"Material Selected Mip",
	"Voxel Geometry Path",
	"Geometry Group",
	"Parallax Pixels",
	"Terrain RVT Hit",
	"Terrain RVT Requested Mip",
	"Terrain RVT Resident Mip",
	"Terrain RVT Virtual Page",
	"Terrain RVT Physical Page",
	"Terrain RVT Page UV",
	"Terrain RVT Atlas Pool",
	"Terrain RVT Atlas UV",
	"Terrain RVT Sampled Albedo",
	"Terrain RVT Fallback Reason",
	"Terrain RVT Owner Page",
	"Terrain RVT Page Delta",
	"Terrain RVT Physical Tile UV",
	"Terrain RVT Sampled Normal",
	"Terrain RVT Sampled Material",
	"Terrain RVT Sampled Albedo Point",
	"Terrain RVT Height Scale",
	"Geometric Height",
	"Terrain Geometric Height Slope",
	"Terrain Dominant Layer",
	"Terrain Dominant Weight",
	"Terrain Texture UV",
	"Terrain Texture Seam",
	"Terrain Paint Grid",
	"Material UV",
	"Material UV Derivative",
	"Reyes Source Barycentrics",
	"Material Eval Features",
	"Terrain Grass Overlay",
	"CLod assembly voxel inheritance",
	"CLod assembly parts",
};
