#pragma once

enum OutputType {
	COLOR = 0,
	NORMAL = 1,
	ALBEDO = 2,
	METALLIC = 3,
	ROUGHNESS = 4,
	EMISSIVE = 5,
	AO = 6,
	DEPTH = 7,
	OUTPUT_DIFFUSE_IBL = 8,
	OUTPUT_SPECULAR_IBL = 9,
	MESHLETS = 10,
	MODEL_NORMAL = 11,
	LIGHT_CLUSTER_ID = 12,
	CLUSTERED_LIGHT_COUNT = 13,
	MOTION_VECTORS = 14,
	SW_RASTER = 15,
	TRANSPARENT_NODE_COUNT = 16,
	TRANSPARENT_DEPTH_COMPLEXITY = 17,
	TRANSPARENT_RESOLVED_SAMPLE_COUNT = 18,
	REYES_GEOMETRY_PATH = 19,
	VSM_PREFERRED_CLIPMAP = 20,
	VSM_SAMPLED_CLIPMAP = 21,
	VSM_PAGE_STATE = 22,
	VSM_PHYSICAL_PAGE = 23,
	VSM_RERENDERED_THIS_FRAME = 24,
	TRANSPARENT_VBOIT_TRANSMITTANCE = 25,
	TRANSPARENT_VBOIT_COVERAGE = 26,
	TRANSPARENT_VBOIT_ZERO_SLICE = 27,
	TRANSPARENT_VBOIT_VIRTUAL_SLICE_COUNT = 28,
	TRANSPARENT_VBOIT_PHYSICAL_SLICE_COUNT = 29,
	TRANSPARENT_VBOIT_FITTED_VIRTUAL_SLICE_COUNT = 30,
	TRANSPARENT_VBOIT_OCCUPIED_VIRTUAL_SLICE_COUNT = 31,
	TRANSPARENT_VBOIT_DEPTH_DISTRIBUTION_EXPONENT = 32,
	MATERIAL_SELECTED_MIP = 33,
	VOXEL_GEOMETRY_PATH = 34,
	GEOMETRY_GROUP = 35,
	PARALLAX_PIXELS = 36,
};

inline std::vector<std::string> OutputTypeNames = {
	"Color",
	"Normal",
	"Albedo",
	"Metallic",
	"Roughness",
	"Emissive",
	"Ambient Occlusion",
	"Depth",
	"Diffuse IBL",
	"Specular IBL",
	"Meshlets",
	"Model Normal",
	"Light Cluster ID",
	"Clustered Light Count",
	"Motion Vectors",
	"SW Raster",
	"Transparent Node Count",
	"Transparent Depth Complexity",
	"Transparent Resolved Sample Count",
	"Reyes Geometry Path",
	"VSM Preferred Clipmap",
	"VSM Sampled Clipmap",
	"VSM Page State",
	"VSM Physical Page",
	"VSM Re-rendered This Frame",
	"Transparent VBOIT Transmittance",
	"Transparent VBOIT Coverage",
	"Transparent VBOIT Zero Slice",
	"Transparent VBOIT Virtual Slice Count",
	"Transparent VBOIT Physical Slice Count",
	"Transparent VBOIT Fitted Virtual Slice Count",
	"Transparent VBOIT Occupied Virtual Slice Count",
	"Transparent VBOIT Depth Distribution Exponent",
	"Material Selected Mip",
	"Voxel Geometry Path",
	"Geometry Group",
	"Parallax Pixels",
};
