#pragma once
enum MaterialFlags {
	MATERIAL_FLAGS_NONE = 0,
	MATERIAL_TEXTURED = 1 << 0,
    MATERIAL_BASE_COLOR_TEXTURE = 1 << 1,
    MATERIAL_NORMAL_MAP = 1 << 2,
    MATERIAL_AO_TEXTURE = 1 << 3,
    MATERIAL_EMISSIVE_TEXTURE = 1 << 4,
    MATERIAL_PBR = 1 << 5,
    MATERIAL_METALLIC_TEXTURE = 1 << 6,
    MATERIAL_ROUGHNESS_TEXTURE = 1 << 7,
    MATERIAL_DOUBLE_SIDED = 1 << 8,
    MATERIAL_PARALLAX = 1 << 9,
	MATERIAL_NEGATE_NORMALS = 1 << 10, // Some normal textures are inverted
	MATERIAL_INVERT_NORMAL_GREEN = 1 << 11, // Some normal textures have inverted green channel
    MATERIAL_OPACITY_TEXTURE = 1 << 12,
	MATERIAL_ALPHA_TEST = 1 << 13,
    MATERIAL_GEOMETRIC_DISPLACEMENT = 1 << 14,
    MATERIAL_TERRAIN = 1 << 15,
    MATERIAL_HEIGHT_FROM_BASE_ALPHA = 1 << 16,
};
