#ifndef __MATERIALFLAGS_HLSL_
#define __MATERIALFLAGS_HLSL_

#define MATERIAL_TEXTURED 1 << 0
#define MATERIAL_BASE_COLOR_TEXTURE 1 << 1
#define MATERIAL_NORMAL_MAP 1 << 2
#define MATERIAL_AO_TEXTURE 1 << 3
#define MATERIAL_EMISSIVE_TEXTURE 1 << 4
#define MATERIAL_PBR 1 << 5
#define MATERIAL_METALLIC_TEXTURE 1 << 6
#define MATERIAL_ROUGHNESS_TEXTURE 1 << 7
#define MATERIAL_DOUBLE_SIDED 1 << 8
#define MATERIAL_PARALLAX 1 << 9
#define MATERIAL_NEGATE_NORMALS 1 << 10
#define MATERIAL_INVERT_NORMAL_GREEN 1 << 11
#define MATERIAL_OPACITY_TEXTURE 1 << 12
#define MATERIAL_ALPHA_TEST 1 << 13
#define MATERIAL_GEOMETRIC_DISPLACEMENT 1 << 14
#define MATERIAL_TERRAIN 1 << 15
#define MATERIAL_HEIGHT_FROM_BASE_ALPHA 1 << 16
#define MATERIAL_OBJECT_SPACE_NORMAL_MAP 1 << 17
#define MATERIAL_OBJECT_TRIPLANAR_STOCHASTIC 1 << 18
#define MATERIAL_OBJECT_TRIPLANAR_STOCHASTIC_BLEND 1 << 19

#endif // __MATERIALFLAGS_HLSL_
