#ifndef __OUTPUT_TYPES_HLSLI__
#define __OUTPUT_TYPES_HLSLI__

// Do enums exist in HLSL?
// The internet disagrees.
// My compiler doesn't like them though
#define OUTPUT_COLOR 0
#define OUTPUT_NORMAL 1
#define OUTPUT_ALBEDO 2
#define OUTPUT_METALLIC 3
#define OUTPUT_ROUGHNESS 4
#define OUTPUT_EMISSIVE 5
#define OUTPUT_AO 6
#define OUTPUT_DEPTH 7
#define OUTPUT_DIFFUSE_IBL 8
#define OUTPUT_SPECULAR_IBL 9
#define OUTPUT_MESHLETS 10
#define OUTPUT_MODEL_NORMALS 11
#define OUTPUT_LIGHT_CLUSTER_ID 12
#define OUTPUT_LIGHT_CLUSTER_LIGHT_COUNT 13
#define OUTPUT_MOTION_VECTORS 14
#define OUTPUT_SW_RASTER 15
#define OUTPUT_TRANSPARENT_NODE_COUNT 16
#define OUTPUT_TRANSPARENT_DEPTH_COMPLEXITY 17
#define OUTPUT_TRANSPARENT_RESOLVED_SAMPLE_COUNT 18
#define OUTPUT_REYES_GEOMETRY_PATH 19
#define OUTPUT_VSM_PREFERRED_CLIPMAP 20
#define OUTPUT_VSM_SAMPLED_CLIPMAP 21
#define OUTPUT_VSM_PAGE_STATE 22
#define OUTPUT_VSM_PHYSICAL_PAGE 23
#define OUTPUT_VSM_RERENDERED_THIS_FRAME 24
#define OUTPUT_TRANSPARENT_VBOIT_TRANSMITTANCE 25
#define OUTPUT_TRANSPARENT_VBOIT_COVERAGE 26
#define OUTPUT_TRANSPARENT_VBOIT_ZERO_SLICE 27
#define OUTPUT_TRANSPARENT_VBOIT_VIRTUAL_SLICE_COUNT 28
#define OUTPUT_TRANSPARENT_VBOIT_PHYSICAL_SLICE_COUNT 29
#define OUTPUT_TRANSPARENT_VBOIT_FITTED_VIRTUAL_SLICE_COUNT 30
#define OUTPUT_TRANSPARENT_VBOIT_OCCUPIED_VIRTUAL_SLICE_COUNT 31
#define OUTPUT_TRANSPARENT_VBOIT_DEPTH_DISTRIBUTION_EXPONENT 32
#define OUTPUT_MATERIAL_SELECTED_MIP 33
#define OUTPUT_VOXEL_GEOMETRY_PATH 34
#define OUTPUT_GEOMETRY_GROUP 35
#define OUTPUT_PARALLAX_PIXELS 36

#endif // __OUTPUT_TYPES_HLSLI__
