#ifndef __OUTPUT_TYPES_HLSLI__
#define __OUTPUT_TYPES_HLSLI__

// Do enums exist in HLSL?
// The internet disagrees.
// My compiler doesn't like them though
#define OUTPUT_COLOR 0
#define OUTPUT_NORMAL 1
#define OUTPUT_ALBEDO 2
#define OUTPUT_METALLIC 3
#define OUTPUT_ROUGHNESS 4
#define OUTPUT_EMISSIVE 5
#define OUTPUT_AO 6
#define OUTPUT_DEPTH 7
#define OUTPUT_DIFFUSE_IBL 8
#define OUTPUT_SPECULAR_IBL 9
#define OUTPUT_MESHLETS 10
#define OUTPUT_MODEL_NORMALS 11
#define OUTPUT_LIGHT_CLUSTER_ID 12
#define OUTPUT_LIGHT_CLUSTER_LIGHT_COUNT 13
#define OUTPUT_MOTION_VECTORS 14
#define OUTPUT_SW_RASTER 15
#define OUTPUT_TRANSPARENT_NODE_COUNT 16
#define OUTPUT_TRANSPARENT_DEPTH_COMPLEXITY 17
#define OUTPUT_TRANSPARENT_RESOLVED_SAMPLE_COUNT 18
#define OUTPUT_REYES_GEOMETRY_PATH 19
#define OUTPUT_VSM_PREFERRED_CLIPMAP 20
#define OUTPUT_VSM_SAMPLED_CLIPMAP 21
#define OUTPUT_VSM_PAGE_STATE 22
#define OUTPUT_VSM_PHYSICAL_PAGE 23
#define OUTPUT_VSM_RERENDERED_THIS_FRAME 24
#define OUTPUT_TRANSPARENT_VBOIT_TRANSMITTANCE 25
#define OUTPUT_TRANSPARENT_VBOIT_COVERAGE 26
#define OUTPUT_TRANSPARENT_VBOIT_ZERO_SLICE 27
#define OUTPUT_TRANSPARENT_VBOIT_VIRTUAL_SLICE_COUNT 28
#define OUTPUT_TRANSPARENT_VBOIT_PHYSICAL_SLICE_COUNT 29
#define OUTPUT_TRANSPARENT_VBOIT_FITTED_VIRTUAL_SLICE_COUNT 30
#define OUTPUT_TRANSPARENT_VBOIT_OCCUPIED_VIRTUAL_SLICE_COUNT 31
#define OUTPUT_TRANSPARENT_VBOIT_DEPTH_DISTRIBUTION_EXPONENT 32
#define OUTPUT_MATERIAL_SELECTED_MIP 33
#define OUTPUT_VOXEL_GEOMETRY_PATH 34
#define OUTPUT_GEOMETRY_GROUP 35
#define OUTPUT_PARALLAX_PIXELS 36
#define OUTPUT_TERRAIN_RVT_HIT 37
#define OUTPUT_TERRAIN_RVT_REQUESTED_MIP 38
#define OUTPUT_TERRAIN_RVT_RESIDENT_MIP 39
#define OUTPUT_TERRAIN_RVT_VIRTUAL_PAGE 40
#define OUTPUT_TERRAIN_RVT_PHYSICAL_PAGE 41
#define OUTPUT_TERRAIN_RVT_PAGE_UV 42
#define OUTPUT_TERRAIN_RVT_ATLAS_POOL 43
#define OUTPUT_TERRAIN_RVT_ATLAS_UV 44
#define OUTPUT_TERRAIN_RVT_SAMPLED_ALBEDO 45
#define OUTPUT_TERRAIN_RVT_FALLBACK_REASON 46
#define OUTPUT_TERRAIN_RVT_OWNER_PAGE 47
#define OUTPUT_TERRAIN_RVT_PAGE_DELTA 48
#define OUTPUT_TERRAIN_RVT_PHYSICAL_TILE_UV 49
#define OUTPUT_TERRAIN_RVT_SAMPLED_NORMAL 50
#define OUTPUT_TERRAIN_RVT_SAMPLED_MATERIAL 51
#define OUTPUT_TERRAIN_RVT_SAMPLED_ALBEDO_POINT 52
#define OUTPUT_TERRAIN_RVT_HEIGHT_SCALE 53
#define OUTPUT_TERRAIN_GEOMETRIC_HEIGHT 54
#define OUTPUT_TERRAIN_GEOMETRIC_HEIGHT_SLOPE 55
#define OUTPUT_TERRAIN_DOMINANT_LAYER 56
#define OUTPUT_TERRAIN_DOMINANT_WEIGHT 57
#define OUTPUT_TERRAIN_TEXTURE_UV 58
#define OUTPUT_TERRAIN_TEXTURE_SEAM 59
#define OUTPUT_TERRAIN_PAINT_GRID 60
#define OUTPUT_MATERIAL_UV 61
#define OUTPUT_MATERIAL_UV_DERIVATIVE 62
#define OUTPUT_REYES_SOURCE_BARYCENTRICS 63
#define OUTPUT_MATERIAL_EVAL_FEATURES 64
#define OUTPUT_TERRAIN_GRASS_OVERLAY 65
#define OUTPUT_CLOD_ASSEMBLY_VOXEL_INHERITANCE 66
#define OUTPUT_CLOD_ASSEMBLY_PARTS 67
#define OUTPUT_SKELETONS 68

#endif // __OUTPUT_TYPES_HLSLI__
